kafka batching
swisspush/gateleen pull request #348
Opened 2021-01-07 15:11 UTC by geekrumper

Instead of waiting for each entry to return a.k.a forcing a sequential flow, we send all messages and let `org.apache.kafka` handle batching with the properties `batch.size` and `linger.ms`.

2021-01-07 15:45 UTC, hiddenalpha commented on gateleen-kafka/src/main/java/org/swisspush/gateleen/kafka/KafkaMessageSender.java
> +        for (KafkaProducerRecord<String, String> message : messages) {
Suggest to log before *for* loop:
```java
log.debug("Start processing {} messages for kafka", messages.size());
```

2021-01-07 15:45 UTC, hiddenalpha commented on gateleen-kafka/src/main/java/org/swisspush/gateleen/kafka/KafkaMessageSender.java
> +                       future.complete();
Suggest to add a log before `future.complete()`:
```java
log.debug("Batch successfully sent to kafka.");
```

2021-01-07 16:25 UTC, hiddenalpha requested changes

2021-01-07 16:25 UTC, hiddenalpha commented on gateleen-kafka/src/main/java/org/swisspush/gateleen/kafka/KafkaMessageSender.java
> +            log.debug("Start processing {} messages for kafka", messages.size());
Please NOT inside the loop. This will print exactly the same log message multiple times.

2021-01-08 11:05 UTC, hiddenalpha approved these changes

2021-01-11 07:43 UTC, mcweba approved these changes

2021-01-11 07:44 UTC, merged